parameters:
    jlog.api_key: '%env(JLOG_API_KEY)%'

services:
    jlog.monolog_handler:
        class: Johndodev\JlogBundle\Monolog\JlogHandler
        public: true
        arguments:
            - '%jlog.api_key%'
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
